
package:
  name: q2-pathway
  version: 2024.5.artifact

source:
  path: ../

build:
  number: 1
  script: make install

requirements:
  build:
    - nodejs

  host:
    - python >=3.9,<3.10
    - setuptools

  run:
    - python >=3.9,<3.10
    - qiime2
    - q2templates
    - q2-types
    - bioconductor-fgsea
    - r-piphir
    - numpy
    - scipy
    - pandas

  about:
    home: https://github.com/noriakis/q2-pathway
    license: BSD-3-Clause
    license_family: BSD
